
--DROP TABLE HOMELIB.IDS;
CREATE TABLE HOMELIB.IDS (
  TABLE_NAME VARCHAR(20) NOT NULL,
  NEXT_ID DECIMAL(30,0) NOT NULL DEFAULT 0,
  PRIMARY KEY (TABLE_NAME)
) ;


--DROP TABLE HOMELIB.LETTCCMMNCLCODE;
CREATE TABLE HOMELIB.LETTCCMMNCLCODE (
  CL_CODE CHAR(3) NOT NULL,
  CL_CODE_NM VARCHAR(60) DEFAULT NULL,
  CL_CODE_DC VARCHAR(200) DEFAULT NULL,
  USE_AT CHAR(1) DEFAULT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT NULL,
  FRST_REGISTER_ID VARCHAR(20) DEFAULT NULL,
  LAST_UPDT_PNTTM DATE DEFAULT NULL,
  LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (CL_CODE)
) ;


--DROP TABLE HOMELIB.LETTCCMMNCODE;
CREATE TABLE HOMELIB.LETTCCMMNCODE (
  CODE_ID VARCHAR(6) NOT NULL,
  CODE_ID_NM VARCHAR(60) DEFAULT NULL,
  CODE_ID_DC VARCHAR(200) DEFAULT NULL,
  USE_AT CHAR(1) DEFAULT NULL,
  CL_CODE CHAR(3) DEFAULT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT NULL,
  FRST_REGISTER_ID VARCHAR(20) DEFAULT NULL,
  LAST_UPDT_PNTTM DATE DEFAULT NULL,
  LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (CODE_ID),
  --KEY R_179 (CL_CODE),
  CONSTRAINT LETTCCMMNCODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES LETTCCMMNCLCODE (CL_CODE)
) ;


--DROP TABLE HOMELIB.LETTCCMMNDETAILCODE;
CREATE TABLE HOMELIB.LETTCCMMNDETAILCODE (
  CODE_ID VARCHAR(6) NOT NULL,
  CODE VARCHAR(15) NOT NULL,
  CODE_NM VARCHAR(60) DEFAULT NULL,
  CODE_DC VARCHAR(200) DEFAULT NULL,
  USE_AT CHAR(1) DEFAULT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT NULL,
  FRST_REGISTER_ID VARCHAR(20) DEFAULT NULL,
  LAST_UPDT_PNTTM DATE DEFAULT NULL,
  LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT LETTCCMMNDETAILCODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES LETTCCMMNCODE (CODE_ID)
) ;


--DROP TABLE HOMELIB.LETTNORGNZTINFO;
CREATE TABLE HOMELIB.LETTNORGNZTINFO (
  ORGNZT_ID CHAR(20) NOT NULL DEFAULT '',
  ORGNZT_NM VARCHAR(20) NOT NULL,
  ORGNZT_DC VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (ORGNZT_ID)
) ;


--DROP TABLE HOMELIB.LETTNAUTHORGROUPINFO;
CREATE TABLE HOMELIB.LETTNAUTHORGROUPINFO (
  GROUP_ID CHAR(20) NOT NULL DEFAULT '',
  GROUP_NM VARCHAR(60) NOT NULL,
  GROUP_CREAT_DE CHAR(20) NOT NULL,
  GROUP_DC VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (GROUP_ID)
) ;


--DROP TABLE HOMELIB.LETTNAUTHORINFO;
CREATE TABLE HOMELIB.LETTNAUTHORINFO (
  AUTHOR_CODE VARCHAR(30) NOT NULL DEFAULT '',
  AUTHOR_NM VARCHAR(60) NOT NULL,
  AUTHOR_DC VARCHAR(200) DEFAULT NULL,
  AUTHOR_CREAT_DE CHAR(20) NOT NULL,
  PRIMARY KEY (AUTHOR_CODE)
) ;


--DROP TABLE HOMELIB.LETTNROLES_HIERARCHY;
CREATE TABLE HOMELIB.LETTNROLES_HIERARCHY (
  PARNTS_ROLE VARCHAR(30) NOT NULL,
  CHLDRN_ROLE VARCHAR(30) NOT NULL,
  PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
  --KEY R_308 (CHLDRN_ROLE),
  CONSTRAINT LETTNROLES_HIERARCHY_ibfk_2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE,
  CONSTRAINT LETTNROLES_HIERARCHY_ibfk_1 FOREIGN KEY (PARNTS_ROLE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE
) ;


--DROP TABLE HOMELIB.LETTNROLEINFO;
CREATE TABLE HOMELIB.LETTNROLEINFO (
  ROLE_CODE VARCHAR(50) NOT NULL DEFAULT '',
  ROLE_NM VARCHAR(60) NOT NULL,
  ROLE_PTTRN VARCHAR(300) DEFAULT NULL,
  ROLE_DC VARCHAR(200) DEFAULT NULL,
  ROLE_TY VARCHAR(80) DEFAULT NULL,
  ROLE_SORT VARCHAR(10) DEFAULT NULL,
  ROLE_CREAT_DE CHAR(20) NOT NULL,
  PRIMARY KEY (ROLE_CODE)
) ;


--DROP TABLE HOMELIB.LETTNAUTHORROLERELATE;
CREATE TABLE HOMELIB.LETTNAUTHORROLERELATE (
  AUTHOR_CODE VARCHAR(30) NOT NULL,
  ROLE_CODE VARCHAR(50) NOT NULL,
  CREAT_DT DATE DEFAULT NULL,
  PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
  --KEY R_292 (ROLE_CODE),
  CONSTRAINT LETTNAUTHORROLERELATE_ibfk_2 FOREIGN KEY (ROLE_CODE) REFERENCES LETTNROLEINFO (ROLE_CODE) ON DELETE CASCADE,
  CONSTRAINT LETTNAUTHORROLERELATE_ibfk_1 FOREIGN KEY (AUTHOR_CODE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE
) ;


--DROP TABLE HOMELIB.LETTNEMPLYRINFO;
CREATE TABLE HOMELIB.LETTNEMPLYRINFO (
  EMPLYR_ID VARCHAR(20) NOT NULL,
  ORGNZT_ID CHAR(20) DEFAULT NULL,
  USER_NM VARCHAR(60) NOT NULL,
  PASSWORD VARCHAR(200) NOT NULL,
  EMPL_NO VARCHAR(20) DEFAULT NULL,
  IHIDNUM VARCHAR(200) DEFAULT NULL,
  SEXDSTN_CODE CHAR(1) DEFAULT NULL,
  BRTHDY CHAR(20) DEFAULT NULL,
  FXNUM VARCHAR(20) DEFAULT NULL,
  HOUSE_ADRES VARCHAR(100) DEFAULT NULL,
  PASSWORD_HINT VARCHAR(100) NOT NULL,
  PASSWORD_CNSR VARCHAR(100) NOT NULL,
  HOUSE_END_TELNO VARCHAR(4) DEFAULT NULL,
  AREA_NO VARCHAR(4) DEFAULT NULL,
  DETAIL_ADRES VARCHAR(100) DEFAULT NULL,
  ZIP VARCHAR(6) DEFAULT NULL,
  OFFM_TELNO VARCHAR(20) DEFAULT NULL,
  MBTLNUM VARCHAR(20) DEFAULT NULL,
  EMAIL_ADRES VARCHAR(50) DEFAULT NULL,
  OFCPS_NM VARCHAR(60) DEFAULT NULL,
  HOUSE_MIDDLE_TELNO VARCHAR(4) DEFAULT NULL,
  GROUP_ID CHAR(20) DEFAULT NULL,
  PSTINST_CODE CHAR(8) DEFAULT NULL,
  EMPLYR_STTUS_CODE VARCHAR(15) NOT NULL,
  ESNTL_ID CHAR(20) NOT NULL,
  CRTFC_DN_VALUE VARCHAR(20) DEFAULT NULL,
  SBSCRB_DE DATE DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID),
  --KEY LETTNEMPLYRINFO_ibfk_2 (GROUP_ID),
  --KEY LETTNEMPLYRINFO_ibfk_1 (ORGNZT_ID),
  CONSTRAINT LETTNEMPLYRINFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT LETTNEMPLYRINFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES LETTNORGNZTINFO (ORGNZT_ID) ON DELETE CASCADE
) ;


--DROP TABLE HOMELIB.LETTNEMPLYRSCRTYESTBS;
CREATE TABLE HOMELIB.LETTNEMPLYRSCRTYESTBS (
  SCRTY_DTRMN_TRGET_ID VARCHAR(20) NOT NULL,
  MBER_TY_CODE VARCHAR(15) DEFAULT NULL,
  AUTHOR_CODE VARCHAR(30) NOT NULL,
  PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  --KEY LETTNEMPLYRSCRTYESTBS_ibfk_4 (AUTHOR_CODE),
  CONSTRAINT LETTNEMPLYRSCRTYESTBS_ibfk_4 FOREIGN KEY (AUTHOR_CODE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE)
) ;


--DROP TABLE HOMELIB.LETTNTMPLATINFO;
CREATE TABLE HOMELIB.LETTNTMPLATINFO (
  TMPLAT_ID CHAR(20) NOT NULL DEFAULT '',
  TMPLAT_NM VARCHAR(255) DEFAULT NULL,
  TMPLAT_COURS VARCHAR(2000) DEFAULT NULL,
  USE_AT CHAR(1) DEFAULT NULL,
  TMPLAT_SE_CODE CHAR(6) DEFAULT NULL,
  FRST_REGISTER_ID VARCHAR(20) DEFAULT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT NULL,
  LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
  LAST_UPDT_PNTTM DATE DEFAULT NULL,
  PRIMARY KEY (TMPLAT_ID)
) ;


--DROP TABLE HOMELIB.LETTNBBSMASTER;
CREATE TABLE HOMELIB.LETTNBBSMASTER (
  BBS_ID CHAR(20) NOT NULL,
  BBS_NM VARCHAR(255) NOT NULL,
  BBS_INTRCN VARCHAR(2400) DEFAULT NULL,
  BBS_TY_CODE CHAR(6) NOT NULL,
  BBS_ATTRB_CODE CHAR(6) NOT NULL,
  REPLY_POSBL_AT CHAR(1) DEFAULT NULL,
  FILE_ATCH_POSBL_AT CHAR(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER DECIMAL(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE DECIMAL(8,0) DEFAULT NULL,
  USE_AT CHAR(1) NOT NULL,
  TMPLAT_ID CHAR(20) DEFAULT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
  LAST_UPDT_PNTTM DATE DEFAULT NULL,
  PRIMARY KEY (BBS_ID)
) ;


--DROP TABLE HOMELIB.LETTNBBSUSE;
CREATE TABLE HOMELIB.LETTNBBSUSE (
  BBS_ID CHAR(20) NOT NULL,
  TRGET_ID CHAR(20) NOT NULL DEFAULT '',
  USE_AT CHAR(1) NOT NULL,
  REGIST_SE_CODE CHAR(6) DEFAULT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM DATE DEFAULT NULL,
  LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT LETTNBBSUSE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ;


--DROP TABLE HOMELIB.LETTNBBS;
CREATE TABLE HOMELIB.LETTNBBS (
  NTT_ID DECIMAL(20,0) NOT NULL,
  BBS_ID CHAR(20) NOT NULL,
  NTT_NO DECIMAL(20,0) DEFAULT NULL,
  NTT_SJ VARCHAR(2000) DEFAULT NULL,
  NTT_CN CLOB(1G),
  ANSWER_AT CHAR(1) DEFAULT NULL,
  PARNTSCTT_NO DECIMAL(10,0) DEFAULT NULL,
  ANSWER_LC NUMERIC(11) DEFAULT NULL,
  SORT_ORDR DECIMAL(8,0) DEFAULT NULL,
  RDCNT DECIMAL(10,0) DEFAULT NULL,
  USE_AT CHAR(1) NOT NULL,
  NTCE_BGNDE CHAR(20) DEFAULT NULL,
  NTCE_ENDDE CHAR(20) DEFAULT NULL,
  NTCR_ID VARCHAR(20) DEFAULT NULL,
  NTCR_NM VARCHAR(20) DEFAULT NULL,
  PASSWORD VARCHAR(200) DEFAULT NULL,
  ATCH_FILE_ID CHAR(20) DEFAULT NULL,
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM DATE DEFAULT NULL,
  LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (NTT_ID,BBS_ID),
  --KEY LETTNBBS_ibfk_1 (BBS_ID),
  CONSTRAINT LETTNBBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ;


--DROP TABLE HOMELIB.LETTCZIP;
CREATE TABLE HOMELIB.LETTCZIP (
  ZIP VARCHAR(6) NOT NULL,
  SN DECIMAL(10,0) NOT NULL DEFAULT 0,
  CTPRVN_NM VARCHAR(20) DEFAULT NULL,
  SIGNGU_NM VARCHAR(20) DEFAULT NULL,
  EMD_NM VARCHAR(60) DEFAULT NULL,
  LI_BULD_NM VARCHAR(60) DEFAULT NULL,
  LNBR_DONG_HO VARCHAR(20) DEFAULT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT NULL,
  FRST_REGISTER_ID VARCHAR(20) DEFAULT NULL,
  LAST_UPDT_PNTTM DATE DEFAULT NULL,
  LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (ZIP,SN)
) ;


--DROP TABLE HOMELIB.LETTHEMPLYRINFOCHANGEDTLS;
CREATE TABLE HOMELIB.LETTHEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID VARCHAR(20) NOT NULL,
  CHANGE_DE DATE NOT NULL,
  ORGNZT_ID CHAR(20) DEFAULT NULL,
  GROUP_ID CHAR(20) DEFAULT NULL,
  EMPL_NO VARCHAR(20) DEFAULT NULL,
  SEXDSTN_CODE CHAR(1) DEFAULT NULL,
  BRTHDY CHAR(20) DEFAULT NULL,
  FXNUM VARCHAR(20) DEFAULT NULL,
  HOUSE_ADRES VARCHAR(100) DEFAULT NULL,
  HOUSE_END_TELNO VARCHAR(4) DEFAULT NULL,
  AREA_NO VARCHAR(4) DEFAULT NULL,
  DETAIL_ADRES VARCHAR(100) DEFAULT NULL,
  ZIP VARCHAR(6) DEFAULT NULL,
  OFFM_TELNO VARCHAR(20) DEFAULT NULL,
  MBTLNUM VARCHAR(20) DEFAULT NULL,
  EMAIL_ADRES VARCHAR(50) DEFAULT NULL,
  HOUSE_MIDDLE_TELNO VARCHAR(4) DEFAULT NULL,
  PSTINST_CODE CHAR(8) DEFAULT NULL,
  EMPLYR_STTUS_CODE VARCHAR(15) DEFAULT NULL,
  ESNTL_ID CHAR(20) DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID,CHANGE_DE)
) ;


--DROP TABLE HOMELIB.LETTNBBSMASTEROPTN;
CREATE TABLE HOMELIB.LETTNBBSMASTEROPTN (
  BBS_ID CHAR(20) NOT NULL DEFAULT '',
  ANSWER_AT CHAR(1) NOT NULL DEFAULT '',
  STSFDG_AT CHAR(1) NOT NULL DEFAULT '',
  FRST_REGIST_PNTTM DATE NOT NULL DEFAULT '1900-01-01 00:00:00', 
  LAST_UPDT_PNTTM DATE DEFAULT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL DEFAULT '',
  LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (BBS_ID)
) ;


--DROP TABLE HOMELIB.LETTNENTRPRSMBER;
CREATE TABLE HOMELIB.LETTNENTRPRSMBER (
  ENTRPRS_MBER_ID VARCHAR(20) NOT NULL DEFAULT '',
  ENTRPRS_SE_CODE CHAR(15) DEFAULT NULL,
  BIZRNO VARCHAR(10) DEFAULT NULL,
  JURIRNO VARCHAR(13) DEFAULT NULL,
  CMPNY_NM VARCHAR(60) NOT NULL,
  CXFC VARCHAR(50) DEFAULT NULL,
  ZIP VARCHAR(6) DEFAULT NULL,
  ADRES VARCHAR(100) DEFAULT NULL,
  ENTRPRS_MIDDLE_TELNO VARCHAR(4) DEFAULT NULL,
  FXNUM VARCHAR(20) DEFAULT NULL,
  INDUTY_CODE CHAR(15) DEFAULT NULL,
  APPLCNT_NM VARCHAR(50) DEFAULT NULL,
  APPLCNT_IHIDNUM VARCHAR(200) DEFAULT NULL,
  SBSCRB_DE DATE DEFAULT NULL,
  ENTRPRS_MBER_STTUS VARCHAR(15) DEFAULT NULL,
  ENTRPRS_MBER_PASSWORD VARCHAR(200) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT VARCHAR(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR VARCHAR(100) NOT NULL,
  GROUP_ID CHAR(20) DEFAULT NULL,
  DETAIL_ADRES VARCHAR(100) DEFAULT NULL,
  ENTRPRS_END_TELNO VARCHAR(4) DEFAULT NULL,
  AREA_NO VARCHAR(4) DEFAULT NULL,
  APPLCNT_EMAIL_ADRES VARCHAR(50) DEFAULT NULL,
  ESNTL_ID CHAR(20) NOT NULL,
  PRIMARY KEY (ENTRPRS_MBER_ID),
  --KEY LETTNENTRPRSMBER_ibfk_1 (GROUP_ID),
  CONSTRAINT LETTNENTRPRSMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;


--DROP TABLE HOMELIB.LETTNFILE;
CREATE TABLE HOMELIB.LETTNFILE (
  ATCH_FILE_ID CHAR(20) NOT NULL,
  CREAT_DT DATE NOT NULL,
  USE_AT CHAR(1) DEFAULT NULL,
  PRIMARY KEY (ATCH_FILE_ID)
) ;


--DROP TABLE HOMELIB.LETTNFILEDETAIL;
CREATE TABLE HOMELIB.LETTNFILEDETAIL (
  ATCH_FILE_ID CHAR(20) NOT NULL,
  FILE_SN decimal(10,0) NOT NULL,
  FILE_STRE_COURS VARCHAR(2000) NOT NULL,
  STRE_FILE_NM VARCHAR(255) NOT NULL,
  ORIGNL_FILE_NM VARCHAR(255) DEFAULT NULL,
  FILE_EXTSN VARCHAR(20) NOT NULL,
  FILE_CN CLOB(1G),
  FILE_SIZE decimal(8,0) DEFAULT NULL,
  PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT LETTNFILEDETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES LETTNFILE (ATCH_FILE_ID)
) ;


--DROP TABLE HOMELIB.LETTNGNRLMBER;
CREATE TABLE HOMELIB.LETTNGNRLMBER (
  MBER_ID VARCHAR(20) NOT NULL DEFAULT '',
  PASSWORD VARCHAR(200) NOT NULL,
  PASSWORD_HINT VARCHAR(100) DEFAULT NULL,
  PASSWORD_CNSR VARCHAR(100) DEFAULT NULL,
  IHIDNUM VARCHAR(200) DEFAULT NULL,
  MBER_NM VARCHAR(50) NOT NULL,
  ZIP VARCHAR(6) DEFAULT NULL,
  ADRES VARCHAR(100) DEFAULT NULL,
  AREA_NO VARCHAR(4) DEFAULT NULL,
  MBER_STTUS VARCHAR(15) DEFAULT NULL,
  DETAIL_ADRES VARCHAR(100) DEFAULT NULL,
  END_TELNO VARCHAR(4) DEFAULT NULL,
  MBTLNUM VARCHAR(20) DEFAULT NULL,
  GROUP_ID char(20) DEFAULT NULL,
  MBER_FXNUM VARCHAR(20) DEFAULT NULL,
  MBER_EMAIL_ADRES VARCHAR(50) DEFAULT NULL,
  MIDDLE_TELNO VARCHAR(4) DEFAULT NULL,
  SBSCRB_DE DATE DEFAULT NULL,
  SEXDSTN_CODE char(1) DEFAULT NULL,
  ESNTL_ID char(20) NOT NULL,
  PRIMARY KEY (MBER_ID),
  --KEY LETTNGNRLMBER_ibfk_1 (GROUP_ID),
  CONSTRAINT LETTNGNRLMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;


--DROP TABLE HOMELIB.LETTNLOGINLOG;
CREATE TABLE HOMELIB.LETTNLOGINLOG (
  LOG_ID char(20) NOT NULL,
  CONECT_ID varchar(20) DEFAULT NULL,
  CONECT_IP varchar(23) DEFAULT NULL,
  CONECT_MTHD char(4) DEFAULT NULL,
  ERROR_OCCRRNC_AT char(1) DEFAULT NULL,
  ERROR_CODE char(3) DEFAULT NULL,
  CREAT_DT DATE DEFAULT NULL,
  PRIMARY KEY (LOG_ID)
) ;


--DROP TABLE HOMELIB.LETTNLOGINPOLICY;
CREATE TABLE HOMELIB.LETTNLOGINPOLICY (
  EMPLYR_ID varchar(20) NOT NULL DEFAULT '',
  IP_INFO varchar(23) NOT NULL,
  DPLCT_PERM_AT char(1) NOT NULL,
  LMTT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM DATE DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID)
) ;


--DROP TABLE HOMELIB.LETTNPROGRMLIST;
CREATE TABLE HOMELIB.LETTNPROGRMLIST (
  PROGRM_FILE_NM varchar(60) NOT NULL DEFAULT '',
  PROGRM_STRE_PATH varchar(100) NOT NULL,
  PROGRM_KOREAN_NM varchar(60) DEFAULT NULL,
  PROGRM_DC varchar(200) DEFAULT NULL,
  URL varchar(100) NOT NULL,
  PRIMARY KEY (PROGRM_FILE_NM)
) ;


--DROP TABLE HOMELIB.LETTNMENUINFO;
CREATE TABLE HOMELIB.LETTNMENUINFO (
  MENU_NM varchar(60) NOT NULL,
  PROGRM_FILE_NM varchar(60) NOT NULL,
  MENU_NO decimal(20,0) NOT NULL,
  UPPER_MENU_NO decimal(20,0) DEFAULT NULL,
  MENU_ORDR decimal(5,0) NOT NULL,
  MENU_DC varchar(250) DEFAULT NULL,
  RELATE_IMAGE_PATH varchar(100) DEFAULT NULL,
  RELATE_IMAGE_NM varchar(60) DEFAULT NULL,
  PRIMARY KEY (MENU_NO),
  --KEY R_2 (PROGRM_FILE_NM),
  --KEY R_4 (UPPER_MENU_NO),
  CONSTRAINT LETTNMENUINFO_ibfk_2 FOREIGN KEY (UPPER_MENU_NO) REFERENCES LETTNMENUINFO (MENU_NO),
  CONSTRAINT LETTNMENUINFO_ibfk_1 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES LETTNPROGRMLIST (PROGRM_FILE_NM) ON DELETE CASCADE
) ;


--DROP TABLE HOMELIB.LETTNMENUCREATDTLS;
CREATE TABLE HOMELIB.LETTNMENUCREATDTLS (
  MENU_NO decimal(20,0) NOT NULL,
  AUTHOR_CODE varchar(30) NOT NULL,
  MAPNG_CREAT_ID varchar(30) DEFAULT NULL,
  PRIMARY KEY (MENU_NO,AUTHOR_CODE),
  --KEY R_247 (MAPNG_CREAT_ID),
  --KEY R_303 (AUTHOR_CODE),
  CONSTRAINT LETTNMENUCREATDTLS_ibfk_3 FOREIGN KEY (AUTHOR_CODE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE),
  CONSTRAINT LETTNMENUCREATDTLS_ibfk_1 FOREIGN KEY (MENU_NO) REFERENCES LETTNMENUINFO (MENU_NO) ON DELETE CASCADE
) ;


--DROP TABLE HOMELIB.LETTNUSERABSNCE;
CREATE TABLE HOMELIB.LETTNUSERABSNCE (
  EMPLYR_ID varchar(20) NOT NULL DEFAULT '',
  USER_ABSNCE_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM DATE DEFAULT NULL,
  PRIMARY KEY (EMPLYR_ID)
) ;


--DROP TABLE HOMELIB.LETTSSYSLOGSUMMARY;
CREATE TABLE HOMELIB.LETTSSYSLOGSUMMARY (
  OCCRRNC_DE char(20) NOT NULL,
  SRVC_NM varchar(255) NOT NULL,
  METHOD_NM varchar(60) NOT NULL,
  CREAT_CO decimal(10,0) DEFAULT NULL,
  UPDT_CO decimal(10,0) DEFAULT NULL,
  RDCNT decimal(10,0) DEFAULT NULL,
  DELETE_CO decimal(10,0) DEFAULT NULL,
  OUTPT_CO decimal(10,0) DEFAULT NULL,
  ERROR_CO decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (OCCRRNC_DE,SRVC_NM,METHOD_NM)
) ;

CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM LETTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNENTRPRSMBER 
;